#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -e


# -- Functions.

append_lines() {
    local file="$1"
    shift
    printf "%s\n" "$@" >> "$file"
}

[ -d /etc/initramfs-tools ] || mkdir -p /etc/initramfs-tools
[ -d /etc/modules-load.d ] || mkdir -p /etc/modules-load.d


# -- Add vfio modules and files to /etc/initramfs-tools/modules.

append_lines /etc/initramfs-tools/modules \
    "softdep nvidia pre: vfio vfio_pci" \
    "softdep nouveau pre: vfio vfio_pci" \
    "softdep amdgpu pre: vfio vfio_pci" \
    "softdep radeon pre: vfio vfio_pci" \
    "softdep i915 pre: vfio vfio_pci" \
    "vfio" \
    "vfio_iommu_type1" \
    "vfio_virqfd" \
    "options vfio_pci ids=" \
    "vfio_pci ids=" \
    "vfio_pci" \
    "nvidia" \
    "nouveau" \
    "amdgpu" \
    "radeon" \
    "i915"


# -- Add vfio modules to /etc/modules-load.d/list-of-vfio-modules.conf to load at boot time.

append_lines /etc/modules-load.d/list-of-vfio-modules.conf \
    "vfio" \
    "vfio_iommu_type1" \
    "vfio_pci" \
    "vfio_pci ids="
